### ISSUE TITLE
How to achieve PoA based on Cosmos SDK

### ISSUE THREAD

**Issue by adust09** [ltacker/supplychainx#1]
Hi @lumtis,  I was just exploring ways to achieve a PoA based on the Cosmos SDK.

I see that this repository is not maintained, are there any plans to update it?
Cosmos SDK version is too old to depinject after v0.5

https://docs.cosmos.network/v0.50/build/building-modules/depinject#integrate-in-an-application

Also, I would like to know how PoA is achieved in zetachain

**Comment by lumtis** [comment]
Hey, this project was for an assignment for a job interview. Most of the codebase is no longer up to date

**Comment by adust09** [comment]
got it, however your team(zetachain) has poa based node, right?

**Comment by lumtis** [comment]
Nope, it's a regular PoS chain

**Comment by adust09** [comment]
I guess I was mistaken. Thanks
